teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 3.0 # m/s
    scale_linear_turbo:
      x: 1.0

    # axis_angular: 0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.3
    scale_angular_turbo:
      yaw: 0.3

    require_enable_button: true
    enable_button: 6  # L2 shoulder button
    enable_turbo_button: 7  # L1 shoulder button
