/lidar:
  ros__parameters:
    hostname: "192.168.0.1"
    frame_id: laser_frame
    scanner_type: sick_tim_7xx
    port: "2112"
    # min_ang: -0.582398 # -2.35619449019
    # max_ang: 2.90699 # 2.35619449019
    range_min: 0.0
    range_max: 25.0
    laserscan_topic: "scan"
    # use_binary_protocol: true

