/lidar:
  ros__parameters:
    hostname: "192.168.0.1"
    frame_id: laser_frame
    scanner_type: sick_tim_7xxS
    min_ang: -2.35619449019
    max_ang: 2.35619449019
    range_min: 0.0
    range_max: 100.0

